import { govukEleventyPlugin } from "@x-govuk/govuk-eleventy-plugin";

import * as filters from "./extract/frontend-components/nunjucks/filters/index.js";
// import * as globals from "./extract/nunjucks/globals/index.js";

/**
 * This function updates this repo to support prototyping and
 * to shared templates and components with the extract-app repo.
 * @param {*} eleventyConfig
 */
const addExtractPrototyping = (eleventyConfig) => {
  // Refresh when the components or layouts change https://www.11ty.dev/docs/watch-serve/#reset-configuration
  eleventyConfig.addWatchTarget("extract", {
    resetConfig: true,
  });

  // add extract and extract/frontend-components to the nunjucks search paths
  // order is important here - extract comes first so its layouts override the ones in extract-app
  eleventyConfig.amendLibrary("njk", (nunjucksLib) => {
    nunjucksLib.loaders[0].searchPaths.push("extract");
    nunjucksLib.loaders[0].searchPaths.push("extract/frontend-components");
  });

  // Allow .js files to be copied to the output folder
  // NB this will affect the /app folder too
  eleventyConfig.addTemplateFormats("js");

  // Passthrough frontend-component assets to prototypes folder in build
  eleventyConfig.addPassthroughCopy({
    "extract/frontend-components/*.css": "prototypes/styles/",
    "extract/frontend-components/*.es.js": "prototypes/scripts/",
  });

  // Custom filters
  Object.keys(filters).forEach((key) => {
    eleventyConfig.addNunjucksFilter(key, filters[key]);
  });
  // // Custom globals
  // Object.keys(globals).forEach((key) => {
  //   eleventyConfig.addNunjucksGlobal(key, globals[key]);
  // });
};

const addGovUkEleventyPlugin = (eleventyConfig) => {
  const isProduction = eleventyConfig.globalData.isProduction || false;
  const pathPrefix = eleventyConfig.globalData.pathPrefix || "/";
  const isSubDirectory = eleventyConfig.globalData.isSubDirectory || false;
  // https://govuk-eleventy-plugin.x-govuk.org/get-started/options/#options-for-search-object
  const search = {
    indexPath: `${pathPrefix}search-index.json`,
    sitemapPath: "/sitemap",
  };
  // https://govuk-eleventy-plugin.x-govuk.org/get-started/options/#options-for-header-object
  const header = {
    productName: "Extract planning data",
    search,
    logotype: {
      text: '<img src="/digital-planning-logo_white.png" alt="Digital Planning logo" height="34" fill="currentcolor" class="govuk-header__logotype"><img src="/i-dot-ai-reverse.svg" alt="i.AI logo" height="30" fill="currentcolor" class="govuk-header__logotype"> ',
    },
  };
  // https://govuk-eleventy-plugin.x-govuk.org/get-started/options/#options-for-footer-object
  const footer = {
    meta: {
      items: [
        {
          href: "/team/",
          text: "Team",
        },
        {
          href: "#",
          text: "Roadmap",
        },
        {
          href: "https://github.com/orgs/digital-land/projects/22/views/4",
          text: "Sprint board",
        },
      ],
    },
  };
  // set the stylesheet to use based on sub-directory or root serve
  const stylesheet = isSubDirectory
    ? "/styles/styles-subdir.css"
    : "/styles/styles.css";
  // register the govukEleventyPlugin

  const config = {
    // override the application.css generated by the gov eleventy plugin
    // so we can set our own stylesheets that include govuk-frontend styles and our site styles
    // and set the correct path for sub-directory or root serve
    stylesheets: [stylesheet],
    markdown: {
      // 	Add links to headings, making it easier to share sections of a page
      headingPermalinks: true,
    },
    // set header options
    header,
    // set footer options
    footer,
    templates: {
      // enables search index generation
      searchIndex: true,
      // Allow readers to browse content by using tags to categorise posts.
      tags: true,
      // Enable RSS feed generation for a collection. https://govuk-eleventy-plugin.x-govuk.org/features/feed/
      feed: {
        title: "Weeknotes for Extract planning data",
        collection: "weeknotes",
        permalink: `/weeknotes/feed.xml`,
      },
    },
  };

  // only set this in production environment not locally in gh-pages mode so local files are loaded
  if (isProduction) {
    config.url = "https://digital-land.github.io/extract-alpha/";
  }

  eleventyConfig.addPlugin(govukEleventyPlugin, config);
};

export default function (eleventyConfig) {
  // Make a flag available to templates indicating a production deploy on main
  // We consider production to be a GitHub Actions run on the `main` branch.
  const isProduction = Boolean(
    process.env.GITHUB_ACTIONS && process.env.GITHUB_REF === "refs/heads/main",
  );

  // Set a flag for whether we are serving in a sub-directory based on GITHUB_ACTIONS env var
  // NB there is a difference between isSubDirectory and isProduction
  const isSubDirectory = Boolean(process.env.GITHUB_ACTIONS);
  const pathPrefix = isSubDirectory ? "/extract-alpha/" : "/";

  // set eleventy globals
  eleventyConfig.addGlobalData("isProduction", isProduction);
  eleventyConfig.addGlobalData("pathPrefix", pathPrefix);
  eleventyConfig.addGlobalData("isSubDirectory", isSubDirectory);

  // setup govuk eleventy plugin
  addGovUkEleventyPlugin(eleventyConfig);

  // Passthrough for images folder used in posts
  eleventyConfig.addPassthroughCopy({ "./app/images": "." });

  // Pass through for files added to the assets folder (excluding dotfiles and junk files)
  // https://github.com/timkendrick/recursive-copy#usage
  eleventyConfig.addPassthroughCopy(
    { "./app/assets": "assets" },
    { dot: false, junk: false },
  );

  // Collections
  eleventyConfig.addCollection("design-history", (collection) => {
    return collection.getFilteredByGlob("app/posts/design-history/*.md");
  });

  eleventyConfig.addCollection("weeknotes", (collection) => {
    return collection.getFilteredByGlob("app/posts/weeknotes/*.md");
  });

  // add extract prototyping things
  addExtractPrototyping(eleventyConfig);

  // when GITHUB_ACTIONS is set, we serve with a path prefix
  return {
    dataTemplateEngine: "njk",
    htmlTemplateEngine: "njk",
    markdownTemplateEngine: "njk",
    pathPrefix,
    dir: {
      input: "app",
      layouts: "_layouts",
      includes: "_components",
    },
    serverOptions: {
      port: 8082,
    },
  };
}
